import simpleGit from "simple-git";
import fs from "fs/promises";
import path from "path";
import { Octokit } from "octokit";

// Helper function to get Octokit instance dynamically (avoids dotenv timing issues)
function getOctokit() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error("GITHUB_TOKEN missing in process.env");
  }
  return new Octokit({ auth: token });
}

// FUNCTION 1: cloneRepo
export async function cloneRepo(repoUrl, localPath) {
  const git = simpleGit();
  await fs.rm(localPath, { recursive: true, force: true }).catch(() => {});
  await git.clone(repoUrl, localPath);
}

// FUNCTION 2: readCodebase (With baseDir tracking)
export async function readCodebase(dirPath, baseDir = dirPath, fileList = []) {
  const files = await fs.readdir(dirPath, { withFileTypes: true });

  for (const file of files) {
    const resPath = path.join(dirPath, file.name);

    if (file.isDirectory()) {
      if (!file.name.startsWith(".") && file.name !== "node_modules") {
        await readCodebase(resPath, baseDir, fileList);
      }
    } else {
      if (
        !file.name.endsWith(".lock") &&
        !file.name.endsWith(".png") &&
        !file.name.endsWith(".ico")
      ) {
        const content = await fs.readFile(resPath, "utf8");
        fileList.push({
          path: path.relative(baseDir, resPath).replace(/\\/g, "/"),
          content,
        });
      }
    }
  }
  return fileList;
}

// FUNCTION 3: applyBatchPatchesAndPush
export async function applyBatchPatchesAndPush(
  localPath,
  commitMessage,
  branchName,
  repoOwner,
  repoName
) {
  const token = process.env.GITHUB_TOKEN;
  const octokit = getOctokit();
  const git = simpleGit(localPath);

  // 1. Git config identity setup
  await git.addConfig("user.name", "OmniDev Bot");
  await git.addConfig("user.email", "bot@omnidev.com");

  // 2. Branch checkout, stage & commit
  await git.checkout(["-B", branchName]);
  await git.add(".");
  await git.commit(commitMessage);

  // 3. Authenticated push (Ensures non-interactive push without SSH/Auth prompt)
  const authenticatedRemote = `https://${token}@github.com/${repoOwner}/${repoName}.git`;
  await git.push(authenticatedRemote, branchName, ["--set-upstream", "--force"]);

  // 4. Default branch auto-detection (main vs master)
  let baseBranch = "main";
  try {
    const { data: repoData } = await octokit.rest.repos.get({
      owner: repoOwner,
      repo: repoName,
    });
    baseBranch = repoData.default_branch || "main";
  } catch (err) {
    console.warn("Default branch detection failed, fallback to 'main':", err.message);
  }

  // 5. Create PR with dynamic base branch & truncated title
  try {
    // Truncate title to max 200 characters to prevent GitHub API 256-char limit validation failure
    const prTitle = commitMessage.length > 200 
      ? `${commitMessage.slice(0, 197)}...` 
      : commitMessage;

    const { data: pr } = await octokit.rest.pulls.create({
      owner: repoOwner,
      repo: repoName,
      title: prTitle,
      head: branchName,
      base: baseBranch,
      body: `Automated Consolidated Pull Request generated by OmniDev AI Software Engineer.\n\n### Task Description:\n${commitMessage}`,
    });
    return pr.html_url;
  } catch (error) {
    if (error.status === 422 || error.message?.includes("A pull request already exists")) {
      console.log("Pull request already exists. Fetching existing PR URL...");
      const { data: existingPrs } = await octokit.rest.pulls.list({
        owner: repoOwner,
        repo: repoName,
        head: `${repoOwner}:${branchName}`,
        state: "open",
      });
      if (existingPrs.length > 0) {
        return existingPrs[0].html_url;
      }
    }
    throw error;
  }
}